### ISSUE TITLE
Kaggle Plankton example problem

### ISSUE THREAD

**Issue by raphaeli** [graphlab-code/graphlab#174]
I run the make_submission.py for the kaggle competition for plankton under Ubuntu
It runs smoothly up to a point and then crushes. Any idea?
```
Python 2.7.9 |Anaconda 2.2.0 (64-bit)| (default, Mar  9 2015, 16:20:48) 
Type "copyright", "credits" or "license" for more information.

IPython 3.0.0 -- An enhanced Interactive Python.
Anaconda is brought to you by Continuum Analytics.
Please check out: http://continuum.io/thanks and https://binstar.org
?         -> Introduction and overview of IPython's features.
%quickref -> Quick reference.
help      -> Python's own help system.
object?   -> Details about 'object', use 'object??' for extra details.
%guiref   -> A brief reference about the graphical user interface.

IIn [2]: run make_submission.py
A newer version of GraphLab Create (v1.3) is available! Your current version is v1.3.0.gpu.
You can use pip to upgrade the graphlab-create package. For more information see https://dato.com/products/create/upgrade.[INFO] Start server at: ipc:///tmp/graphlab_server-23031 - Server binary: /home/midas/anaconda_2/lib/python2.7/site-packages/graphlab/unity_server - Server log: /tmp/graphlab_server_1428320002.log
[INFO] GraphLab Server Version: 1.3.0.gpu
Loading images...
Resizing images...
Data Augmentation...
Training Model...
Using network:

### network layers ###
layer[0]: ConvolutionLayer
  init_random = gaussian
  padding = 2
  stride = 4
  num_channels = 96
  num_groups = 1
  kernel_size = 5
layer[1]: RectifiedLinearLayer
layer[2]: MaxPoolingLayer
  padding = 0
  stride = 2
  kernel_size = 3
layer[3]: ConvolutionLayer
  init_random = gaussian
  padding = 2
  stride = 1
  num_channels = 128
  num_groups = 1
  kernel_size = 3
layer[4]: RectifiedLinearLayer
layer[5]: ConvolutionLayer
  init_random = gaussian
  padding = 1
  stride = 1
  num_channels = 128
  num_groups = 1
  kernel_size = 3
layer[6]: RectifiedLinearLayer
layer[7]: MaxPoolingLayer
  padding = 0
  stride = 2
  kernel_size = 3
layer[8]: FlattenLayer
layer[9]: FullConnectionLayer
  init_sigma = 0.01
  init_random = gaussian
  init_bias = 0
  num_hidden_units = 512
layer[10]: RectifiedLinearLayer
layer[11]: DropoutLayer
  threshold = 0.5
layer[12]: FullConnectionLayer
  init_sigma = 0.01
  init_random = gaussian
  init_bias = 0
  num_hidden_units = 512
layer[13]: RectifiedLinearLayer
layer[14]: DropoutLayer
  threshold = 0.5
layer[15]: FullConnectionLayer
  init_sigma = 0.01
  init_random = gaussian
  init_bias = 0
  num_hidden_units = 121
layer[16]: SoftmaxLayer
### end network layers ###

### network parameters ###
init_random = xavier
random_mirror = 1
learning_rate = 0.01
input_shape = 3,48,48
learning_rate_gamma = 0.1
bias_learning_rate = 0.02
init_sigma = 0.01
batch_size = 256
learning_rate_step = 10000
random_crop = 1
learning_rate_schedule = exponential_decay
l2_regularization = 0.0005
momentum = 0.9
bias_l2_regularization = 0.0
### end network parameters ###

Traceback (most recent call last):

  File "/home/midas/kaggle/bowl4/make_submission.py", line 140, in <module>
    random_crop=True)

  File "/home/midas/anaconda_2/lib/python2.7/site-packages/graphlab/toolkits/classifier/neuralnet_classifier.py", line 976, in create
    **(_network.params))

  File "/home/midas/anaconda_2/lib/python2.7/site-packages/graphlab/toolkits/_supervised_learning.py", line 359, in create
    validation_set.head().append(dataset.head())

  File "/home/midas/anaconda_2/lib/python2.7/site-packages/graphlab/data_structures/sframe.py", line 3350, in append
    raise RuntimeError("Two SFrames have to have the same number of columns")

RuntimeError: Two SFrames have to have the same number of columns
```

**Comment by dbickson** [comment]
HI, 
We would love to help you but you posted the issue in the wrong repository. This repo is for PowerGrpah code. Can you send me your email so we would communicate directly? Or even better if you can repost the question on http://forum.dato.com
